name: Main workflow

on: [push]

jobs:
  linting:
    name:  run static code analysis
    uses : ./.github/workflows/ci-lint.yml

  tests:
    name : run test
    needs: linting
    uses : ./.github/workflows/ci-test.yml
  
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Cache Docker layers
      #   uses: actions/cache@v2
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-

      # - name: Build and push Docker image
      #   run: |
      #     docker build -t bienfait/budget-app-image:v1.0.0 .
      #     docker push bienfait/budget-app-image:v1.0.0
      
      - name: Login to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DIGITALOCEAN_SERVER_IP }} 
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: my_rsa_keys
          script: |
            cd budget-app-backend  
            git pull